name:                hs-llvm-tutorial
version:             0.1.0.0
homepage:            https://github.com/DylanSp/hs-llvm-tutorial#readme
license:             MIT
author:              Dylan Sprague
maintainer:          dylan.richard.sprague@gmail.com
copyright:           2018 Dylan Sprague
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - parsec

executables:
  hs-llvm-tutorial:
    source-dirs:      src
    main:             Main.hs
